### ISSUE TITLE
Restyle News/Blog page template

### ISSUE THREAD

**Issue by travisward** [AgriLife/agriflex4#1]
All AF4 variants should use the new news format as seen on agrilife.org
This should impact archive.php (archives, blog page, categories, tags)

Example using old format (running af4-agrilife-unit): 
https://cers.tamu.edu/funding-opportunity-news/

**Comment by ZachWatkins** [comment]
Right now the changes for archive pages are done with WordPress and Genesis hooks and filters instead of through a custom archive.php template file. I will modify the existing implementation so that if the blog page is not the home page then it will display like the post and taxonomy archive pages, since that is the faster solution.
